import '../models/exercise.dart';

/// Seed data for the exercise library. Written to exercises.json on first run.
const List<Exercise> defaultExercises = [
  // ── Push ──────────────────────────────────────────────
  Exercise(
    id: 'bench_press_barbell',
    name: 'Bench Press (Barbell)',
    category: MuscleCategory.push,
    type: ExerciseType.weighted,
    equipment: 'barbell',
    defaultRestSeconds: 180,
  ),
  Exercise(
    id: 'bench_press_dumbbell',
    name: 'Bench Press (Dumbbell)',
    category: MuscleCategory.push,
    type: ExerciseType.weighted,
    equipment: 'dumbbell',
    defaultRestSeconds: 150,
  ),
  Exercise(
    id: 'overhead_press_barbell',
    name: 'Overhead Press (Barbell)',
    category: MuscleCategory.push,
    type: ExerciseType.weighted,
    equipment: 'barbell',
    defaultRestSeconds: 180,
  ),
  Exercise(
    id: 'overhead_press_dumbbell',
    name: 'Overhead Press (Dumbbell)',
    category: MuscleCategory.push,
    type: ExerciseType.weighted,
    equipment: 'dumbbell',
    defaultRestSeconds: 150,
  ),
  Exercise(
    id: 'incline_bench_press',
    name: 'Incline Bench Press',
    category: MuscleCategory.push,
    type: ExerciseType.weighted,
    equipment: 'barbell',
    defaultRestSeconds: 150,
  ),
  Exercise(
    id: 'dip',
    name: 'Dip',
    category: MuscleCategory.push,
    type: ExerciseType.bodweightPlus,
    equipment: 'dip bar',
    defaultRestSeconds: 120,
  ),
  Exercise(
    id: 'push_up',
    name: 'Push-up',
    category: MuscleCategory.push,
    type: ExerciseType.bodyweight,
    equipment: 'bodyweight',
    defaultRestSeconds: 90,
  ),
  Exercise(
    id: 'lateral_raise',
    name: 'Lateral Raise',
    category: MuscleCategory.push,
    type: ExerciseType.weighted,
    equipment: 'dumbbell',
    defaultRestSeconds: 90,
  ),
  Exercise(
    id: 'tricep_pushdown',
    name: 'Tricep Pushdown',
    category: MuscleCategory.push,
    type: ExerciseType.weighted,
    equipment: 'cable',
    defaultRestSeconds: 90,
  ),

  // ── Pull ──────────────────────────────────────────────
  Exercise(
    id: 'pull_up',
    name: 'Pull-up',
    category: MuscleCategory.pull,
    type: ExerciseType.bodweightPlus,
    equipment: 'pull-up bar',
    defaultRestSeconds: 150,
  ),
  Exercise(
    id: 'chin_up',
    name: 'Chin-up',
    category: MuscleCategory.pull,
    type: ExerciseType.bodweightPlus,
    equipment: 'pull-up bar',
    defaultRestSeconds: 150,
  ),
  Exercise(
    id: 'barbell_row',
    name: 'Barbell Row',
    category: MuscleCategory.pull,
    type: ExerciseType.weighted,
    equipment: 'barbell',
    defaultRestSeconds: 180,
  ),
  Exercise(
    id: 'dumbbell_row',
    name: 'Dumbbell Row',
    category: MuscleCategory.pull,
    type: ExerciseType.weighted,
    equipment: 'dumbbell',
    defaultRestSeconds: 120,
  ),
  Exercise(
    id: 'lat_pulldown',
    name: 'Lat Pulldown',
    category: MuscleCategory.pull,
    type: ExerciseType.weighted,
    equipment: 'cable',
    defaultRestSeconds: 120,
  ),
  Exercise(
    id: 'face_pull',
    name: 'Face Pull',
    category: MuscleCategory.pull,
    type: ExerciseType.weighted,
    equipment: 'cable',
    defaultRestSeconds: 90,
  ),
  Exercise(
    id: 'bicep_curl_barbell',
    name: 'Bicep Curl (Barbell)',
    category: MuscleCategory.pull,
    type: ExerciseType.weighted,
    equipment: 'barbell',
    defaultRestSeconds: 90,
  ),
  Exercise(
    id: 'bicep_curl_dumbbell',
    name: 'Bicep Curl (Dumbbell)',
    category: MuscleCategory.pull,
    type: ExerciseType.weighted,
    equipment: 'dumbbell',
    defaultRestSeconds: 90,
  ),
  Exercise(
    id: 'deadlift',
    name: 'Deadlift',
    category: MuscleCategory.pull,
    type: ExerciseType.weighted,
    equipment: 'barbell',
    defaultRestSeconds: 240,
  ),

  // ── Legs ──────────────────────────────────────────────
  Exercise(
    id: 'squat_barbell',
    name: 'Squat (Barbell)',
    category: MuscleCategory.legs,
    type: ExerciseType.weighted,
    equipment: 'barbell',
    defaultRestSeconds: 240,
  ),
  Exercise(
    id: 'leg_press',
    name: 'Leg Press',
    category: MuscleCategory.legs,
    type: ExerciseType.weighted,
    equipment: 'machine',
    defaultRestSeconds: 180,
  ),
  Exercise(
    id: 'romanian_deadlift',
    name: 'Romanian Deadlift',
    category: MuscleCategory.legs,
    type: ExerciseType.weighted,
    equipment: 'barbell',
    defaultRestSeconds: 180,
  ),
  Exercise(
    id: 'leg_curl',
    name: 'Leg Curl',
    category: MuscleCategory.legs,
    type: ExerciseType.weighted,
    equipment: 'machine',
    defaultRestSeconds: 120,
  ),
  Exercise(
    id: 'leg_extension',
    name: 'Leg Extension',
    category: MuscleCategory.legs,
    type: ExerciseType.weighted,
    equipment: 'machine',
    defaultRestSeconds: 120,
  ),
  Exercise(
    id: 'lunge',
    name: 'Lunge',
    category: MuscleCategory.legs,
    type: ExerciseType.weighted,
    equipment: 'dumbbell',
    defaultRestSeconds: 120,
  ),
  Exercise(
    id: 'calf_raise',
    name: 'Calf Raise',
    category: MuscleCategory.legs,
    type: ExerciseType.weighted,
    equipment: 'machine',
    defaultRestSeconds: 90,
  ),

  // ── Core ──────────────────────────────────────────────
  Exercise(
    id: 'plank',
    name: 'Plank',
    category: MuscleCategory.core,
    type: ExerciseType.bodyweight,
    equipment: 'bodyweight',
    defaultRestSeconds: 60,
  ),
  Exercise(
    id: 'ab_wheel',
    name: 'Ab Wheel',
    category: MuscleCategory.core,
    type: ExerciseType.bodyweight,
    equipment: 'ab wheel',
    defaultRestSeconds: 90,
  ),
  Exercise(
    id: 'hanging_leg_raise',
    name: 'Hanging Leg Raise',
    category: MuscleCategory.core,
    type: ExerciseType.bodyweight,
    equipment: 'pull-up bar',
    defaultRestSeconds: 90,
  ),

  // ── Cardio ────────────────────────────────────────────
  Exercise(
    id: 'running',
    name: 'Running',
    category: MuscleCategory.cardio,
    type: ExerciseType.cardio,
    equipment: 'none',
    defaultRestSeconds: 0,
  ),
  Exercise(
    id: 'rowing',
    name: 'Rowing (Erg)',
    category: MuscleCategory.cardio,
    type: ExerciseType.cardio,
    equipment: 'rower',
    defaultRestSeconds: 0,
  ),
  Exercise(
    id: 'cycling',
    name: 'Cycling',
    category: MuscleCategory.cardio,
    type: ExerciseType.cardio,
    equipment: 'bike',
    defaultRestSeconds: 0,
  ),
  Exercise(
    id: 'jump_rope',
    name: 'Jump Rope',
    category: MuscleCategory.cardio,
    type: ExerciseType.cardio,
    equipment: 'jump rope',
    defaultRestSeconds: 60,
  ),

  // ── Kettlebell ────────────────────────────────────────
  Exercise(
    id: 'kettlebell_swing',
    name: 'Kettlebell Swing',
    category: MuscleCategory.full,
    type: ExerciseType.weighted,
    equipment: 'kettlebell',
    defaultRestSeconds: 90,
  ),
  Exercise(
    id: 'turkish_get_up',
    name: 'Turkish Get-up',
    category: MuscleCategory.full,
    type: ExerciseType.weighted,
    equipment: 'kettlebell',
    defaultRestSeconds: 120,
  ),
];
